export {LandingPage} from './landingpage/landingpage'
export {LoginPage} from './authenticationPages/loginpage/loginpage'
export {SignUpPage} from './authenticationPages/signupPage/signupPage'
export {NotesPage} from './notesPage/notesPage'
export {ArchivePage} from './archivePage/archivePage'
export {TrashPage} from './trashPage/trashPage'
export {LabelPage} from './labelPage/labelPage'